/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { usePolicyStore } from "../../store/usePolicyStore";
import { useDamageStore } from "../../store/useDamageStore";
import type { GLTF } from "three-stdlib";
import { useRef, useMemo } from "react";
import type { ThreeElement, ThreeEvent } from "@react-three/fiber";
import * as THREE from "three";
import { LoopSubdivision } from "three-subdivide";

const CLICK_THRESHOLD_MS = 200;
const CLICK_THRESHOLD_PX = 4;

type GLTFResult = GLTF & {
  nodes: {
    Cylinder: THREE.Mesh;
    Cylinder001: THREE.Mesh;
    Cylinder002: THREE.Mesh;
    Cylinder003: THREE.Mesh;
    AirWent: THREE.Mesh;
    Bottom: THREE.Mesh;
    Camera_front: THREE.Mesh;
    LightsFront: THREE.Mesh;
    LightsRear: THREE.Mesh;
    Plane023: THREE.Mesh;
    "select-back-door-frame-right": THREE.Mesh;
    "select-back-door-frameleft": THREE.Mesh;
    "select-back-door-left": THREE.Mesh;
    "select-back-door-right": THREE.Mesh;
    "select-back-window-right": THREE.Mesh;
    "select-back-window-left": THREE.Mesh;
    "select-front-window-right": THREE.Mesh;
    "select-front-window-left": THREE.Mesh;
    "select-boot": THREE.Mesh;
    "select-front-bumper": THREE.Mesh;
    "select-front-door-frame-left": THREE.Mesh;
    "select-front-door-frame-right": THREE.Mesh;
    "select-front-door-left": THREE.Mesh;
    "select-front-door-right": THREE.Mesh;
    "select-hood": THREE.Mesh;
    "select-left-mirror": THREE.Mesh;
    "select-right-mirror": THREE.Mesh;
    "select-window-top": THREE.Mesh;
    "select-back-bumper": THREE.Mesh;
    BreakDisc003: THREE.Mesh;
    RimAreo003: THREE.Mesh;
    BreakDisc001: THREE.Mesh;
    RimAreo001: THREE.Mesh;
    BreakDisc004: THREE.Mesh;
    RimAreo004: THREE.Mesh;
    BreakDisc002: THREE.Mesh;
    RimAreo002: THREE.Mesh;
    windowtrim: THREE.Mesh;
    windowtrim2: THREE.Mesh;
    Windows003: THREE.Mesh;
  };
  materials: {
    "Tire LP": THREE.Material;
    "Grill LP": THREE.Material;
    LightAbsorber: THREE.Material;
    "Indicaters LP": THREE.Material;
    "Lights LP": THREE.Material;
    "Metalic LP": THREE.Material;
    "Car Paint LP": THREE.Material;
    "Glass LP": THREE.Material;
    "Mirrors LP": THREE.Material;
    brakes: THREE.Material;
    "Rims LP": THREE.Material;
  };
};

function usePanelProps(
  panel: import("../../store/useDamageStore").CarPanel,
  baseMaterial: THREE.Material,
  damagedMaterial: THREE.Material,
) {
  const { damagedPanels, toggleDamage } = useDamageStore();
  const pointerDown = useRef<{ x: number; y: number; time: number } | null>(
    null,
  );

  return {
    material: damagedPanels.has(panel) ? damagedMaterial : baseMaterial,
    onPointerDown: (e: ThreeEvent<PointerEvent>) => {
      e.stopPropagation();
      pointerDown.current = { x: e.clientX, y: e.clientY, time: Date.now() };
    },
    onPointerUp: (e: ThreeEvent<PointerEvent>) => {
      e.stopPropagation();
      if (!pointerDown.current) return;
      const dx = Math.abs(e.clientX - pointerDown.current.x);
      const dy = Math.abs(e.clientY - pointerDown.current.y);
      const dt = Date.now() - pointerDown.current.time;
      pointerDown.current = null;
      if (
        dt > CLICK_THRESHOLD_MS ||
        dx > CLICK_THRESHOLD_PX ||
        dy > CLICK_THRESHOLD_PX
      )
        return;
      toggleDamage(panel);
    },
  };
}

const damagedMaterial = new THREE.MeshStandardMaterial({ color: "#22c55e" });

export default function Model(props: ThreeElement<typeof THREE.Group>) {
  const { nodes, materials } = useGLTF("/tesla2.glb") as unknown as GLTFResult;
  const colour = usePolicyStore((s) => s.colour);
  const carPaintMaterial = new THREE.MeshStandardMaterial({
    ...(materials["Car Paint LP"] as THREE.MeshStandardMaterial),
    color:
      colour || (materials["Car Paint LP"] as THREE.MeshStandardMaterial).color,
  });

  const rearRightDoor = usePanelProps(
    "rear-right-door",
    carPaintMaterial,
    damagedMaterial,
  );
  const rearLeftDoor = usePanelProps(
    "rear-left-door",
    carPaintMaterial,
    damagedMaterial,
  );
  const trunk = usePanelProps("trunk", carPaintMaterial, damagedMaterial);
  const frontBumper = usePanelProps(
    "front-bumper",
    carPaintMaterial,
    damagedMaterial,
  );
  const frontLeftDoor = usePanelProps(
    "front-left-door",
    carPaintMaterial,
    damagedMaterial,
  );
  const frontRightDoor = usePanelProps(
    "front-right-door",
    carPaintMaterial,
    damagedMaterial,
  );
  const hood = usePanelProps("hood", carPaintMaterial, damagedMaterial);
  const frontLeftMirror = usePanelProps(
    "front-left-mirror",
    carPaintMaterial,
    damagedMaterial,
  );
  const frontRightMirror = usePanelProps(
    "front-right-mirror",
    carPaintMaterial,
    damagedMaterial,
  );
  const windshield = usePanelProps(
    "windshield",
    materials["Glass LP"],
    damagedMaterial,
  );
  const rearBumper = usePanelProps(
    "rear-bumper",
    carPaintMaterial,
    damagedMaterial,
  );
  const rearRightWindow = usePanelProps(
    "rear-right-window",
    materials["Glass LP"],
    damagedMaterial,
  );
  const rearLeftWindow = usePanelProps(
    "rear-left-window",
    materials["Glass LP"],
    damagedMaterial,
  );
  const frontRightWindow = usePanelProps(
    "front-right-window",
    materials["Glass LP"],
    damagedMaterial,
  );
  const frontLeftWindow = usePanelProps(
    "front-left-window",
    materials["Glass LP"],
    damagedMaterial,
  );
  const smoothHoodGeometry = useMemo(() => {
    return LoopSubdivision.modify(nodes["select-hood"].geometry, 2, {
      split: false,
      uvSmooth: false,
      preserveEdges: true,
    });
  }, [nodes]);
  const smoothFrontBumperGeometry = useMemo(() => {
    return LoopSubdivision.modify(nodes["select-front-bumper"].geometry, 2, {
      split: false,
      uvSmooth: false,
      preserveEdges: true,
    });
  }, [nodes]);
  const smoothBackBumperGeometry = useMemo(() => {
    return LoopSubdivision.modify(nodes["select-back-bumper"].geometry, 2, {
      split: false,
      uvSmooth: false,
      preserveEdges: true,
    });
  }, [nodes]);
  const smoothBootGeometry = useMemo(() => {
    return LoopSubdivision.modify(nodes["select-boot"].geometry, 2, {
      split: false,
      uvSmooth: false,
      preserveEdges: true,
    });
  }, [nodes]);
  const smoothWindowTopGeometry = useMemo(() => {
    return LoopSubdivision.modify(nodes["select-window-top"].geometry, 2, {
      split: false,
      uvSmooth: false,
      preserveEdges: true,
    });
  }, [nodes]);
  const subdivOpts = { split: false, uvSmooth: false, preserveEdges: true };
  const smoothBackDoorFrameRightGeometry = useMemo(() => LoopSubdivision.modify(nodes["select-back-door-frame-right"].geometry, 2, subdivOpts), [nodes]);
  const smoothBackDoorFrameLeftGeometry = useMemo(() => LoopSubdivision.modify(nodes["select-back-door-frameleft"].geometry, 2, subdivOpts), [nodes]);
  const smoothBackDoorLeftGeometry = useMemo(() => LoopSubdivision.modify(nodes["select-back-door-left"].geometry, 2, subdivOpts), [nodes]);
  const smoothBackDoorRightGeometry = useMemo(() => LoopSubdivision.modify(nodes["select-back-door-right"].geometry, 2, subdivOpts), [nodes]);
  const smoothFrontDoorFrameLeftGeometry = useMemo(() => LoopSubdivision.modify(nodes["select-front-door-frame-left"].geometry, 2, subdivOpts), [nodes]);
  const smoothFrontDoorFrameRightGeometry = useMemo(() => LoopSubdivision.modify(nodes["select-front-door-frame-right"].geometry, 2, subdivOpts), [nodes]);
  const smoothFrontDoorLeftGeometry = useMemo(() => LoopSubdivision.modify(nodes["select-front-door-left"].geometry, 2, subdivOpts), [nodes]);
  const smoothFrontDoorRightGeometry = useMemo(() => LoopSubdivision.modify(nodes["select-front-door-right"].geometry, 2, subdivOpts), [nodes]);
  const smoothLeftMirrorGeometry = useMemo(() => LoopSubdivision.modify(nodes["select-left-mirror"].geometry, 2, subdivOpts), [nodes]);
  const smoothRightMirrorGeometry = useMemo(() => LoopSubdivision.modify(nodes["select-right-mirror"].geometry, 2, subdivOpts), [nodes]);
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder.geometry}
        material={materials["Tire LP"]}
        position={[0.774, -0.316, 1.389]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.359, 0.146, 0.359]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder001.geometry}
        material={materials["Tire LP"]}
        position={[0.774, -0.316, -1.55]}
        rotation={[0, 0, -Math.PI / 2]}
        scale={[0.359, 0.146, 0.359]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder002.geometry}
        material={materials["Tire LP"]}
        position={[-0.771, -0.316, -1.547]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={[0.359, 0.146, 0.359]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Cylinder003.geometry}
        material={materials["Tire LP"]}
        position={[-0.771, -0.316, 1.391]}
        rotation={[Math.PI, 0, Math.PI / 2]}
        scale={[0.359, 0.146, 0.359]}
      />
      <group position={[0, -0.673, 0]} scale={2.394}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AirWent.geometry}
          material={materials["Grill LP"]}
          position={[0, 0.146, -0.914]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.044, 0.152, 0.005]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bottom.geometry}
          material={materials.LightAbsorber}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Camera_front.geometry}
          material={materials["Indicaters LP"]}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LightsFront.geometry}
          material={materials["Lights LP"]}
          position={[0, 0.153, 0.576]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={[0.418, 0.417, 0.417]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LightsRear.geometry}
          material={materials["Lights LP"]}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothBackBumperGeometry}
          {...rearBumper}
          position={[0, 0.153, 0.576]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothBackDoorFrameRightGeometry}
          {...rearRightDoor}
          position={[0, 0.153, 0.576]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothBackDoorFrameLeftGeometry}
          {...rearLeftDoor}
          position={[0, 0.153, 0.576]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothBackDoorLeftGeometry}
          {...rearLeftDoor}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothBackDoorRightGeometry}
          {...rearRightDoor}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["select-back-window-left"].geometry}
          {...rearLeftWindow}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["select-back-window-right"].geometry}
          {...rearRightWindow}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["select-boot"].geometry}
          {...trunk}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothFrontBumperGeometry}
          {...frontBumper}
          position={[0, 0.153, 0.576]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothFrontDoorFrameLeftGeometry}
          {...frontLeftDoor}
          position={[0, 0.153, 0.576]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothFrontDoorFrameRightGeometry}
          {...frontRightDoor}
          position={[0, 0.153, 0.576]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothFrontDoorLeftGeometry}
          {...frontLeftDoor}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothFrontDoorRightGeometry}
          {...frontRightDoor}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["select-front-window-left"].geometry}
          {...frontLeftWindow}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes["select-front-window-right"].geometry}
          {...frontRightWindow}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothHoodGeometry}
          {...hood}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothLeftMirrorGeometry}
          {...frontLeftMirror}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.417}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothRightMirrorGeometry}
          {...frontRightMirror}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.417}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothWindowTopGeometry}
          {...windshield}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <group
          position={[-0.326, 0.149, -0.645]}
          rotation={[0, -1.571, 0]}
          scale={0.417}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BreakDisc003.geometry}
            material={materials.brakes}
            position={[0, 0, 0.028]}
            rotation={[-Math.PI, 0, 0]}
            scale={-0.7}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.RimAreo003.geometry}
            material={materials["Rims LP"]}
            position={[0, 0, 0.105]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={0.263}
          />
        </group>
        <group
          position={[0.326, 0.149, -0.645]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.417}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BreakDisc001.geometry}
            material={materials.brakes}
            position={[0, 0, 0.028]}
            scale={0.7}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.RimAreo001.geometry}
            material={materials["Rims LP"]}
            position={[0, 0, 0.105]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={0.263}
          />
        </group>
        <group
          position={[-0.326, 0.149, 0.58]}
          rotation={[0, -1.571, 0]}
          scale={0.417}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BreakDisc004.geometry}
            material={materials.brakes}
            position={[0, 0, 0.028]}
            scale={0.7}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.RimAreo004.geometry}
            material={materials["Rims LP"]}
            position={[0, 0, 0.105]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={0.263}
          />
        </group>
        <group
          position={[0.326, 0.149, 0.58]}
          rotation={[0, 1.571, 0]}
          scale={0.417}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BreakDisc002.geometry}
            material={materials.brakes}
            position={[0, 0, 0.028]}
            rotation={[-Math.PI, 0, 0]}
            scale={-0.7}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.RimAreo002.geometry}
            material={materials["Rims LP"]}
            position={[0, 0, 0.105]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={0.263}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.windowtrim.geometry}
          material={materials["Metalic LP"]}
          position={[0, 0.153, 0.576]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0.004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.windowtrim2.geometry}
          material={materials.LightAbsorber}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
      </group>
    </group>
  );
}

useGLTF.preload("/tesla2.glb");
