/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import { useGLTF } from "@react-three/drei";
import { usePolicyStore } from "../../store/usePolicyStore";
import { useDamageStore } from "../../store/useDamageStore";
import type { GLTF } from "three-stdlib";
import { useRef, useMemo } from "react";
import type { ThreeElement, ThreeEvent } from "@react-three/fiber";
import * as THREE from "three";
import { LoopSubdivision } from "three-subdivide";

const CLICK_THRESHOLD_MS = 200;
const CLICK_THRESHOLD_PX = 4;

type GLTFResult = GLTF & {
  nodes: {
    AirVent: THREE.Mesh;
    AirVentHood: THREE.Mesh;
    Boot: THREE.Mesh;
    Bottom: THREE.Mesh;
    BumperFront: THREE.Mesh;
    BumperRear: THREE.Mesh;
    CameraFront: THREE.Mesh;
    ChairFront: THREE.Mesh;
    ChairRear: THREE.Mesh;
    Dashboard: THREE.Mesh;
    DoorFrontHandleLeft: THREE.Mesh;
    DoorFrontHandleRight: THREE.Mesh;
    DoorFrontLeft: THREE.Mesh;
    DoorFrontRight: THREE.Mesh;
    DoorRearLeft: THREE.Mesh;
    DoorRearRight: THREE.Mesh;
    HeadLightsFrontLeft: THREE.Mesh;
    HeadLightsFrontRight: THREE.Mesh;
    Hood: THREE.Mesh;
    Interior: THREE.Mesh;
    InteriorBoot: THREE.Mesh;
    InteriorDoorFront: THREE.Mesh;
    InteriorDoorRear: THREE.Mesh;
    InteriorMiddle: THREE.Mesh;
    InteriorMirror: THREE.Mesh;
    InteriorOnBoardComputer: THREE.Mesh;
    InteriorSteeringWheel: THREE.Mesh;
    LightsFront: THREE.Mesh;
    LightsRear: THREE.Mesh;
    MirrorLeft: THREE.Mesh;
    MirrorRight: THREE.Mesh;
    PanelFrontLeft: THREE.Mesh;
    PanelFrontRight: THREE.Mesh;
    PanelRearLeft: THREE.Mesh;
    PanelRearLeft001: THREE.Mesh;
    PanelRearRight: THREE.Mesh;
    RoofPanel01: THREE.Mesh;
    RoofPanel02: THREE.Mesh;
    TailLightsRearLeft: THREE.Mesh;
    TailLightsRearRight: THREE.Mesh;
    BreakDisc003: THREE.Mesh;
    RimAreo003: THREE.Mesh;
    BreakDisc001: THREE.Mesh;
    RimAreo001: THREE.Mesh;
    BreakDisc004: THREE.Mesh;
    RimAreo004: THREE.Mesh;
    BreakDisc002: THREE.Mesh;
    RimAreo002: THREE.Mesh;
    WindowFrontLeft: THREE.Mesh;
    WindowFrontRight: THREE.Mesh;
    WindowPanelleft: THREE.Mesh;
    WindowPanelRight: THREE.Mesh;
    WindowPanelTrim: THREE.Mesh;
    WindowPanelTrimBottom: THREE.Mesh;
    WindowRearLeft: THREE.Mesh;
    WindowRearRight: THREE.Mesh;
    WindowRoof: THREE.Mesh;
    tyres_rear: THREE.Mesh;
    tyres_front: THREE.Mesh;
    RegoBorderRear: THREE.Mesh;
    RegoFaceRear: THREE.Mesh;
    RegoBorderFront: THREE.Mesh;
    RegoFaceFront: THREE.Mesh;
  };
  materials: {
    Alloy: THREE.Material;
    Tires: THREE.Material;
    Body: THREE.Material;
    Windows: THREE.Material;
  };
};

function usePanelProps(
  panel: import("../../store/useDamageStore").CarPanel,
  baseMaterial: THREE.Material,
  damagedMaterial: THREE.Material,
) {
  const { damagedPanels, toggleDamage } = useDamageStore();
  const pointerDown = useRef<{ x: number; y: number; time: number } | null>(
    null,
  );

  return {
    material: damagedPanels.has(panel) ? damagedMaterial : baseMaterial,
    onPointerDown: (e: ThreeEvent<PointerEvent>) => {
      e.stopPropagation();
      pointerDown.current = { x: e.clientX, y: e.clientY, time: Date.now() };
    },
    onPointerUp: (e: ThreeEvent<PointerEvent>) => {
      e.stopPropagation();
      if (!pointerDown.current) return;
      const dx = Math.abs(e.clientX - pointerDown.current.x);
      const dy = Math.abs(e.clientY - pointerDown.current.y);
      const dt = Date.now() - pointerDown.current.time;
      pointerDown.current = null;
      if (
        dt > CLICK_THRESHOLD_MS ||
        dx > CLICK_THRESHOLD_PX ||
        dy > CLICK_THRESHOLD_PX
      )
        return;
      toggleDamage(panel);
    },
  };
}

const damagedMaterial = new THREE.MeshStandardMaterial({ color: "#a20000" });

function usePlateTexture(registration: string) {
  return useMemo(() => {
    const canvas = document.createElement("canvas");
    canvas.width = 512;
    canvas.height = 128;
    const ctx = canvas.getContext("2d")!;

    ctx.fillStyle = "#ffffff";
    ctx.fillRect(0, 0, 512, 128);

    ctx.save();
    ctx.translate(0, 128);
    ctx.scale(1, -1);
    ctx.fillStyle = "#000000";
    ctx.font = 'bold 88px "Arial Black", Arial, sans-serif';
    ctx.textAlign = "center";
    ctx.textBaseline = "middle";
    ctx.fillText(registration.toUpperCase(), 256, 69);
    ctx.restore();

    const texture = new THREE.CanvasTexture(canvas);
    return new THREE.MeshStandardMaterial({ map: texture });
  }, [registration]);
}

export default function Model(props: ThreeElement<typeof THREE.Group>) {
  const { nodes, materials } = useGLTF("/tesla5.glb") as unknown as GLTFResult;
  const colour = usePolicyStore((s) => s.colour);
  const registration = usePolicyStore((s) => s.registration);
  const frontPlateMaterial = usePlateTexture(registration);
  const rearPlateMaterial = usePlateTexture(registration);
  const carPaintMaterial = new THREE.MeshStandardMaterial({
    ...(materials.Body as THREE.MeshStandardMaterial),
    color: colour || (materials.Body as THREE.MeshStandardMaterial).color,
  });

  const rearRightDoor = usePanelProps(
    "rear-right-door",
    carPaintMaterial,
    damagedMaterial,
  );
  const rearLeftDoor = usePanelProps(
    "rear-left-door",
    carPaintMaterial,
    damagedMaterial,
  );
  const trunk = usePanelProps("trunk", carPaintMaterial, damagedMaterial);
  const frontBumper = usePanelProps(
    "front-bumper",
    carPaintMaterial,
    damagedMaterial,
  );
  const frontLeftDoor = usePanelProps(
    "front-left-door",
    carPaintMaterial,
    damagedMaterial,
  );
  const frontRightDoor = usePanelProps(
    "front-right-door",
    carPaintMaterial,
    damagedMaterial,
  );
  const hood = usePanelProps("hood", carPaintMaterial, damagedMaterial);
  const frontLeftMirror = usePanelProps(
    "front-left-mirror",
    carPaintMaterial,
    damagedMaterial,
  );
  const frontRightMirror = usePanelProps(
    "front-right-mirror",
    carPaintMaterial,
    damagedMaterial,
  );
  const damagedWindowMaterial = useMemo(() => {
    const mat = (materials.Windows as THREE.MeshStandardMaterial).clone();
    mat.color.set("#a20000");
    return mat;
  }, [materials.Windows]);

  const windshield = usePanelProps(
    "windshield",
    materials["Windows"],
    damagedWindowMaterial,
  );
  const rearBumper = usePanelProps(
    "rear-bumper",
    carPaintMaterial,
    damagedMaterial,
  );
  const rearRightWindow = usePanelProps(
    "rear-right-window",
    materials["Windows"],
    damagedWindowMaterial,
  );
  const rearLeftWindow = usePanelProps(
    "rear-left-window",
    materials["Windows"],
    damagedWindowMaterial,
  );
  const frontRightWindow = usePanelProps(
    "front-right-window",
    materials["Windows"],
    damagedWindowMaterial,
  );
  const frontLeftWindow = usePanelProps(
    "front-left-window",
    materials["Windows"],
    damagedWindowMaterial,
  );
  const frontLeftHeadlight = usePanelProps(
    "front-left-headlight",
    materials["Windows"],
    damagedWindowMaterial,
  );
  const frontRightHeadlight = usePanelProps(
    "front-right-headlight",
    materials["Windows"],
    damagedWindowMaterial,
  );
  const rearLeftTaillight = usePanelProps(
    "rear-left-taillight",
    materials["Windows"],
    damagedWindowMaterial,
  );
  const rearRightTaillight = usePanelProps(
    "rear-right-taillight",
    materials["Windows"],
    damagedWindowMaterial,
  );

  const subdivOpts = { split: false, uvSmooth: false, preserveEdges: true };

  const smoothHoodGeometry = useMemo(
    () => LoopSubdivision.modify(nodes.Hood.geometry, 2, subdivOpts),
    [nodes],
  );
  const smoothFrontBumperGeometry = useMemo(
    () => LoopSubdivision.modify(nodes.BumperFront.geometry, 1, subdivOpts),
    [nodes],
  );
  const smoothRearBumperGeometry = useMemo(
    () => LoopSubdivision.modify(nodes.BumperRear.geometry, 1, subdivOpts),
    [nodes],
  );
  const smoothBootGeometry = useMemo(
    () => LoopSubdivision.modify(nodes.Boot.geometry, 0, subdivOpts),
    [nodes],
  );
  const smoothWindowRoofGeometry = useMemo(
    () => LoopSubdivision.modify(nodes.WindowRoof.geometry, 2, subdivOpts),
    [nodes],
  );
  const smoothDoorFrontLeftGeometry = useMemo(
    () => LoopSubdivision.modify(nodes.DoorFrontLeft.geometry, 2, subdivOpts),
    [nodes],
  );
  const smoothDoorFrontRightGeometry = useMemo(
    () => LoopSubdivision.modify(nodes.DoorFrontRight.geometry, 2, subdivOpts),
    [nodes],
  );
  const smoothDoorRearLeftGeometry = useMemo(
    () => LoopSubdivision.modify(nodes.DoorRearLeft.geometry, 2, subdivOpts),
    [nodes],
  );
  const smoothDoorRearRightGeometry = useMemo(
    () => LoopSubdivision.modify(nodes.DoorRearRight.geometry, 2, subdivOpts),
    [nodes],
  );
  const smoothMirrorLeftGeometry = useMemo(
    () => LoopSubdivision.modify(nodes.MirrorLeft.geometry, 1, subdivOpts),
    [nodes],
  );
  const smoothMirrorRightGeometry = useMemo(
    () => LoopSubdivision.modify(nodes.MirrorRight.geometry, 1, subdivOpts),
    [nodes],
  );

  return (
    <group {...props} dispose={null}>
      <group scale={2.394}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AirVent.geometry}
          material={materials.Alloy}
          position={[0, 0.146, -0.914]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.044, 0.152, 0.005]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.AirVentHood.geometry}
          material={materials.Tires}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothBootGeometry}
          {...trunk}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Bottom.geometry}
          material={materials.Tires}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothFrontBumperGeometry}
          {...frontBumper}
          position={[0, 0.153, 0.576]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothRearBumperGeometry}
          {...rearBumper}
          position={[0, 0.153, 0.576]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.CameraFront.geometry}
          material={materials.Windows}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ChairFront.geometry}
          material={nodes.ChairFront.material}
          position={[-0.173, 0.171, -0.102]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.417}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.ChairRear.geometry}
          material={nodes.ChairRear.material}
          position={[0, 0.244, 0.354]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={[0.461, 0.417, 0.417]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Dashboard.geometry}
          material={nodes.Dashboard.material}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DoorFrontHandleLeft.geometry}
          material={materials.Tires}
          position={[-0.372, 0.368, 0.222]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.DoorFrontHandleRight.geometry}
          material={materials.Tires}
          position={[-0.37, 0.368, 0.222]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothDoorFrontLeftGeometry}
          {...frontLeftDoor}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothDoorFrontRightGeometry}
          {...frontRightDoor}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothDoorRearLeftGeometry}
          {...rearLeftDoor}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothDoorRearRightGeometry}
          {...rearRightDoor}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HeadLightsFrontLeft.geometry}
          {...frontLeftHeadlight}
          position={[0, 0.153, 0.576]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={[0.418, 0.417, 0.417]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.HeadLightsFrontRight.geometry}
          {...frontRightHeadlight}
          position={[0, 0.153, 0.576]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={[0.418, 0.417, 0.417]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothHoodGeometry}
          {...hood}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Interior.geometry}
          material={nodes.Interior.material}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.InteriorBoot.geometry}
          material={nodes.InteriorBoot.material}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.417}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.InteriorDoorFront.geometry}
          material={nodes.InteriorDoorFront.material}
          position={[0, 0.151, 0.577]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.InteriorDoorRear.geometry}
          material={nodes.InteriorDoorRear.material}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.InteriorMiddle.geometry}
          material={nodes.InteriorMiddle.material}
          position={[0, 0.157, -0.252]}
          rotation={[-Math.PI, 0, -Math.PI]}
          scale={0.056}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.InteriorMirror.geometry}
          material={nodes.InteriorMirror.material}
          position={[0, 0.553, -0.148]}
          rotation={[2.793, 0, -Math.PI]}
          scale={0.052}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.InteriorOnBoardComputer.geometry}
          material={nodes.InteriorOnBoardComputer.material}
          position={[0, 0.37, -0.335]}
          rotation={[-1.745, 0, Math.PI]}
          scale={0.417}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.InteriorSteeringWheel.geometry}
          material={nodes.InteriorSteeringWheel.material}
          position={[-0.175, 0.356, -0.364]}
          rotation={[2.967, 0, -Math.PI]}
          scale={[-0.014, -0.016, -0.012]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LightsFront.geometry}
          material={materials.Windows}
          position={[0, 0.153, 0.576]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={[0.418, 0.417, 0.417]}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LightsRear.geometry}
          material={materials.Windows}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothMirrorLeftGeometry}
          {...frontLeftMirror}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.417}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothMirrorRightGeometry}
          {...frontRightMirror}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.417}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PanelFrontLeft.geometry}
          {...frontLeftDoor}
          position={[0, 0.153, 0.576]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PanelFrontRight.geometry}
          {...frontRightDoor}
          position={[0, 0.153, 0.576]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PanelRearLeft.geometry}
          {...rearLeftDoor}
          position={[0, 0.153, 0.576]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PanelRearLeft001.geometry}
          {...rearLeftDoor}
          position={[0, 0.153, 0.576]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.PanelRearRight.geometry}
          {...rearRightDoor}
          position={[0, 0.153, 0.576]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RoofPanel01.geometry}
          material={materials.Tires}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.RoofPanel02.geometry}
          material={materials.Tires}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.TailLightsRearLeft.geometry}
          {...rearLeftTaillight}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.TailLightsRearRight.geometry}
          {...rearRightTaillight}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <group
          position={[-0.326, 0.149, -0.645]}
          rotation={[0, -1.571, 0]}
          scale={0.417}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BreakDisc003.geometry}
            material={materials.Alloy}
            position={[0, 0, 0.028]}
            rotation={[-Math.PI, 0, 0]}
            scale={-0.7}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.RimAreo003.geometry}
            material={materials.Alloy}
            position={[0, 0, 0.105]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={0.263}
          />
        </group>
        <group
          position={[0.326, 0.149, -0.645]}
          rotation={[0, Math.PI / 2, 0]}
          scale={0.417}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BreakDisc001.geometry}
            material={materials.Alloy}
            position={[0, 0, 0.028]}
            scale={0.7}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.RimAreo001.geometry}
            material={materials.Alloy}
            position={[0, 0, 0.105]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={0.263}
          />
        </group>
        <group
          position={[-0.326, 0.149, 0.58]}
          rotation={[0, -1.571, 0]}
          scale={0.417}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BreakDisc004.geometry}
            material={materials.Alloy}
            position={[0, 0, 0.028]}
            scale={0.7}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.RimAreo004.geometry}
            material={materials.Alloy}
            position={[0, 0, 0.105]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={0.263}
          />
        </group>
        <group
          position={[0.326, 0.149, 0.58]}
          rotation={[0, 1.571, 0]}
          scale={0.417}
        >
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.BreakDisc002.geometry}
            material={materials.Alloy}
            position={[0, 0, 0.028]}
            rotation={[-Math.PI, 0, 0]}
            scale={-0.7}
          />
          <mesh
            castShadow
            receiveShadow
            geometry={nodes.RimAreo002.geometry}
            material={materials.Alloy}
            position={[0, 0, 0.105]}
            rotation={[-Math.PI / 2, Math.PI / 2, 0]}
            scale={0.263}
          />
        </group>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WindowFrontLeft.geometry}
          {...frontLeftWindow}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WindowFrontRight.geometry}
          {...frontRightWindow}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WindowPanelleft.geometry}
          material={materials.Tires}
          position={[0, 0.153, 0.576]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WindowPanelRight.geometry}
          material={materials.Tires}
          position={[0, 0.153, 0.576]}
          rotation={[Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WindowPanelTrim.geometry}
          material={nodes.WindowPanelTrim.material}
          position={[0, 0.153, 0.576]}
          rotation={[0, 0, Math.PI / 2]}
          scale={0.004}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WindowPanelTrimBottom.geometry}
          material={nodes.WindowPanelTrimBottom.material}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WindowRearLeft.geometry}
          {...rearLeftWindow}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.WindowRearRight.geometry}
          {...rearRightWindow}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={smoothWindowRoofGeometry}
          {...windshield}
          position={[0, 0.153, 0.576]}
          rotation={[-Math.PI, 0, Math.PI / 2]}
          scale={0.177}
        />
      </group>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tyres_rear.geometry}
        material={materials.Tires}
        position={[-0.778, 0.357, 1.388]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.tyres_front.geometry}
        material={materials.Tires}
        position={[-0.778, 0.357, -1.547]}
        rotation={[Math.PI / 2, 0, -Math.PI / 2]}
      />
      {/* <mesh
        castShadow
        receiveShadow
        geometry={nodes.RegoBorderRear.geometry}
        material={materials.Tires}
        position={[0, 0.76, 2.273]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RegoFaceRear.geometry}
        material={rearPlateMaterial}
        position={[0, 0.76, 2.273]}
        scale={[0.94, 0.87, 0.3]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RegoBorderFront.geometry}
        material={materials.Tires}
        position={[0, 0.47, -2.312]}
        rotation={[-Math.PI, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RegoFaceFront.geometry}
        material={frontPlateMaterial}
        position={[0, 0.47, -2.311]}
        rotation={[-Math.PI, 0, 0]}
        scale={[0.94, 0.87, 0.3]}
      /> */}
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RegoBorderRear.geometry}
        material={materials.Tires}
        position={[0, 0.76, 2.273]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RegoBorderFront.geometry}
        material={materials.Tires}
        position={[0, 0.47, -2.312]}
        rotation={[-Math.PI, 0, 0]}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RegoFaceRear.geometry}
        material={rearPlateMaterial}
      />
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.RegoFaceFront.geometry}
        material={frontPlateMaterial}
      />
    </group>
  );
}

useGLTF.preload("/tesla5.glb");
